services:
  app:
    build: .
    container_name: rediska_app
    ports:
      - "4000:4000"
    depends_on:
      - redis
    environment:
      - MIX_ENV=dev
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: ./run.sh

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always